#!/usr/bin/env python3
# -*- coding: utf-8 -*-
'''Import (restore) tabs from tabs_backup.json onto a macOS machine.
Opens tabs into new windows of Chrome and/or Firefox using AppleScript and 'open -a'.
Usage:
  python3 import_tabs.py tabs_backup.json [--chrome] [--firefox]
If no browser flags provided, both are attempted.
'''
import argparse, json, os, subprocess, sys, time, glob

def run_jxa(script: str, argv_json: str = None) -> str:
    cmd = ['osascript', '-l', 'JavaScript', '-e', script]
    if argv_json is not None:
        # Pass an extra 'run' invocation with argv
        script += "\nrun([JSON.stringify(" + argv_json + ")])"
        cmd = ['osascript', '-l', 'JavaScript', '-e', script]
    p = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return p.stdout.strip()

def open_chrome_window(urls):
    if not urls: 
        return
    jxa = '''
    function run(argv) {
      var urls = JSON.parse(argv[0]);
      var chrome = Application('Google Chrome');
      chrome.activate();
      var w = chrome.Window().make();
      w.tabs.push(chrome.Tab({url: urls[0]}));
      for (var i=1;i<urls.length;i++){
        w.tabs.push(chrome.Tab({url: urls[i]}));
      }
      w.activeTabIndex = 1;
      return String(urls.length);
    }
    '''
    run_jxa(jxa, json.dumps(urls))

def open_firefox_window(urls):
    if not urls: 
        return
    for u in urls:
        subprocess.run(['open', '-a', 'Firefox', u])
        time.sleep(0.1)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('backup_json', help='Path to tabs_backup.json generated by export_tabs.py (or directory containing it)')
    ap.add_argument('--chrome', action='store_true', help='Restore into Chrome')
    ap.add_argument('--firefox', action='store_true', help='Restore into Firefox')
    args = ap.parse_args()

    # Handle case where backup_json is a directory
    json_path = args.backup_json
    if os.path.isdir(json_path):
        candidates = glob.glob(os.path.join(json_path, '*.json'))
        preferred = os.path.join(json_path, 'tabs_backup.json')
        if preferred in candidates:
            json_path = preferred
        elif candidates:
            json_path = candidates[0]
        else:
            print(f'[ERROR] No JSON files found in directory: {json_path}', file=sys.stderr)
            sys.exit(1)
    elif not os.path.exists(json_path):
        print(f'[ERROR] File or directory not found: {json_path}', file=sys.stderr)
        sys.exit(1)

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    if not args.chrome and not args.firefox:
        args.chrome = True
        args.firefox = True

    chrome_windows = [w for w in data if w.get('browser') == 'chrome']
    firefox_windows = [w for w in data if w.get('browser') == 'firefox']

    if args.chrome:
        for w in chrome_windows:
            urls = [t.get('url') for t in w.get('tabs', []) if t.get('url')]
            open_chrome_window(urls)

    if args.firefox:
        for w in firefox_windows:
            urls = [t.get('url') for t in w.get('tabs', []) if t.get('url')]
            open_firefox_window(urls)

    print('[OK] Restore complete.')

if __name__ == '__main__':
    main()
